sequenceDiagram
    autonumber
    actor Paciente as Paciente
    participant WA as WhatsApp/Solicitud impresa
    actor Recepcion as Recepcionista (Chatwoot / WhatsApp Web)
    participant Sistema as Sistema Bloc Digital
    participant LIS as Sistema Admin. Existente
    actor Medico as Médico Tratante

    Paciente->>WA: Muestra Folio digital o impreso
    WA->>Recepcion: Dicta Folio o Nombre
    Recepcion->>Sistema: Localiza solicitud por #Folio
    Sistema-->>Recepcion: Muestra información
    Recepcion->>Sistema: Da clic en "En Atención"
    Sistema-->>Medico: Actualiza estatus en Tablero Médico al instante
    Recepcion->>LIS: Captura venta e inicia proceso de laboratorio (Interno)
