flowchart LR
    %% Estilos de Nodos
    classDef rol fill:#EDF2F7,stroke:#4A5568,stroke-width:2px,font-weight:bold,color:#2D3748;
    classDef portal fill:#EBF8FF,stroke:#2B6CB0,stroke-width:2px,color:#2B6CB0,font-weight:bold;
    classDef estado fill:#FEFCBF,stroke:#B7791F,stroke-width:2px,color:#975A16,font-weight:bold;

    subgraph Medicos_Emision [Área Médica - Emisión]
        M1[Médico Tratante]:::rol
        PM1[Portal Médico<br>laesh.mx/medicos]:::portal
    end

    subgraph Paciente_Inicio [Paciente - Emisión]
        P1[Paciente con Orden]:::rol
    end

    subgraph Clinica [Área de Recepción]
        R[Recepcionista]:::rol
        PR[Portal de Recepción<br>laesh.mx/labadmin]:::portal
    end

    subgraph Medicos_Cierre [Área Médica - Consulta]
        PM2[Portal Médico<br>laesh.mx/medicos]:::portal
        M2[Médico Tratante]:::rol
    end

    subgraph Paciente_Fin [Paciente - Cierre]
        P2[Paciente con Resultados]:::rol
    end

    subgraph BD [Base de Datos / Estados de la Orden]
        E1(Estado: Remitido):::estado
        E2(Estado: En Atención):::estado
        E3(Estado: Resultados Listos):::estado
        E4(Estado: Cerrada):::estado
    end

    %% Alineación Vertical de Pools (para escalonado descendente)
    M1 ~~~ P1 ~~~ R ~~~ E1

    %% Flujo Operativo de Izquierda a Derecha (LR) con numeración corregida 1-13
    M1 -->|1. Captura Orden| PM1
    PM1 -->|2. Genera Folio| E1
    E1 -->|3. Entrega Hoja Física| P1
    PM1 -.->|4. Notificación Silbato| PR
    P1 -->|5. Acude a la clínica| R
    R -->|6. Busca Paciente| PR
    PR -->|7. Cambia a En Atención| E2
    E2 -->|8 y 9. Toma de muestras y Carga PDF| E3
    E3 -.->|10. Alerta PDF Silenciosa| PM2
    PM2 -->|11. Médico descarga PDF| M2
    E3 -->|12. Entrega resultados impresos| P2
    R -->|13. Cierre de Orden| E4

    %% Estilos de Líneas (Colores por etapa de flujo)
    linkStyle 0 stroke:#3182ce,stroke-width:2.5px;
    linkStyle 1 stroke:#3182ce,stroke-width:2.5px;
    linkStyle 2 stroke:#3182ce,stroke-width:2.5px;
    linkStyle 3 stroke:#dd6b20,stroke-width:2.5px,stroke-dasharray: 4;
    linkStyle 4 stroke:#38a169,stroke-width:2.5px;
    linkStyle 5 stroke:#38a169,stroke-width:2.5px;
    linkStyle 6 stroke:#38a169,stroke-width:2.5px;
    linkStyle 7 stroke:#805ad5,stroke-width:2.5px;
    linkStyle 8 stroke:#805ad5,stroke-width:2.5px,stroke-dasharray: 4;
    linkStyle 9 stroke:#805ad5,stroke-width:2.5px;
    linkStyle 10 stroke:#718096,stroke-width:2.5px;
    linkStyle 11 stroke:#718096,stroke-width:2.5px;
