DROP DATABASE IF EXISTS `vcd01`;
CREATE DATABASE `vcd01` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'vcd01'@'%' IDENTIFIED BY 'vcd01';
GRANT ALL PRIVILEGES ON `vcd01`.* TO 'vcd01'@'%';
FLUSH PRIVILEGES;
