sequenceDiagram
    autonumber
    participant S as Notificador automatizado para WhatsApp
    actor P as Paciente
    actor R as Recepción (Chatwoot)
    
    S->>P: Notifica Orden clínica digital en imagen con Botón
    Note over S, P: Estado: Fuera de ventana (Texto libre bloqueado)
    P-->>S: Paciente oprime botón: [Ver Horarios y Ubicación]
    Note over S, P: Meta registra el clic como interacción válida
    Note over S, P: ¡Se abre Ventana de Servicio (24h)! 🟢
    R->>P: Recepción atiende libremente si el paciente tiene más dudas
